nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - db
    volumes_from:
        - app

app:
    image: php:7.0-fpm
    volumes:
        - D:\Docker\shearevolume\public_html:/var/www/html
    command: "true"

db:
    image: mariadb:10.3
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: 1234

data:
    image: mariadb:10.3
    volumes:
        - D:\Docker\shearevolume\mysql:/var/lib/mysql
    command: "true"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8000:80
    links:
        - db
#    environment:
#        PMA_HOST: mysql
